version: '3'

includes:
  test: tasks/Taskfile.test.yaml

env:
  ATOMI_SERVICE: Boron

tasks:
  setup:
    desc: 'Setup the repository'
    cmds:
      - dotnet restore
      - ./scripts/local/secrets.sh

  build:
    desc: 'Build the library'
    cmds:
      - dotnet build
