version: '3'

includes:
  unit:
    taskfile: tasks/Taskfile.test.yaml
    vars:
      TEST_DIR: UnitTest
      TARGET: Boron
  int:
    taskfile: tasks/Taskfile.test.yaml
    vars:
      TEST_DIR: IntTest
      TARGET: Boron

env:
  ATOMI_SERVICE: Boron

tasks:
  setup:
    desc: 'Setup the repository'
    cmds:
      - dotnet restore
      - dotnet tool restore
      - ./scripts/secrets.sh

  build:
    desc: 'Build the library'
    cmds:
      - dotnet build

  deps:
    desc: 'Update all dependencies'
    cmds:
      - dotnet outdated -u:prompt
