name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: AtomiCloud/ketone.nuget/.github/reusable/precommit.yaml@main
    with:
      atomi_platform: carboxylic
      atomi_service: boron

  unit-test:
    name: UnitTest
    uses: AtomiCloud/ketone.nuget/.github/reusable/tests.yaml@main
    with:
      atomi_platform: carboxylic
      atomi_service: boron
      test_dir: UnitTest
      target: Boron

  int-test:
    name: IntTest
    uses: AtomiCloud/ketone.nuget/.github/reusable/tests.yaml@main
    with:
      atomi_platform: carboxylic
      atomi_service: boron
      test_dir: IntTest
      target: Boron
