name: CI

on:
  push:

jobs:
  precommit:
    name: Pre-Commit
    uses: ./.github/workflows/reusable-precommit.yaml
    secrets: inherit
    with:
      atomi_platform: carboxylic
      atomi_service: boron

  unit-test:
    name: UnitTest
    uses: ./.github/workflows/reusable-tests.yaml
    secrets: inherit
    with:
      atomi_platform: carboxylic
      atomi_service: boron
      test_dir: UnitTest
      target: Boron

  int-test:
    name: IntTest
    uses: ./.github/workflows/reusable-tests.yaml
    secrets: inherit
    with:
      atomi_platform: carboxylic
      atomi_service: boron
      test_dir: IntTest
      target: Boron
