name: Release

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed

concurrency:
  group: release

jobs:
  release:
    name: Semantic Release
    uses: ./.github/workflows/reusable-release.yaml
    secrets: inherit
    with:
      atomi_platform: carboxylic
      atomi_service: boron
