name: Release

on:
  workflow_run:
    workflows: ['CI']
    branches: [main]
    types:
      - completed

concurrency:
  group: release

jobs:
  release:
    name: Semantic Release
    uses: AtomiCloud/ketone.nuget/.github/workflows/reusable/release.yaml@main
    with:
      atomi_platform: carboxylic
      atomi_service: boron
